project:
  type: book
  output-dir: "output"
  execute-dir: project

sources:
  base: D:\jan_zill\EET_Phase11C\eet_inconsistency_investigation\data\output\output-base-eet
  ## transit
  # affected_zones: D:\jan_zill\EET_Phase11C\eet_inconsistency_investigation\data\inputs\transit_corridor\transit_zones_affected.csv
  # build: D:\jan_zill\EET_Phase11C\eet_inconsistency_investigation\data\output\output-transit-eet
  # how_method: all # Employment -> any, Transit -> all
  ## employment
  affected_zones: D:\jan_zill\EET_Phase11C\eet_inconsistency_investigation\data\inputs\employment\employment_zones_affected.csv
  build: D:\jan_zill\EET_Phase11C\eet_inconsistency_investigation\data\output\output-employment-eet
  how_method: any # Employment -> any, Transit -> all

  notebooks:
  - long_term.ipynb
  - daily.ipynb
  - joint.ipynb
  - tours.ipynb
  - trips.ipynb

book:
  title: "ActivitySim Base-Build Comparison Visualization"
  repo-url: https://github.com/outerl/asim_eet_viz
  repo-branch: jzill/phase11c
  search: false

  chapters:
    - index.qmd

number-sections: true
format:
  html:
    mainfont: sans-serif
    fontsize: "7"
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    echo: false
    code-tools: true
    # output-file: visualization
    embed-resources: false
toc: true
warning: false
