[project]
name = "asim-eet-viz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.0",
    "polars>=1.31.0",
    "polars-lts-cpu>=1.31.0",
    "pyarrow>=20.0.0",
    "openpyxl",
    "openmatrix",
    "plotly",
    "jupyterlab",
    "ipykernel>=7.3.0",
    "nbparameterise>=0.6.1",
]
